import { defineManifest } from "@crxjs/vite-plugin";

export default defineManifest({
  manifest_version: 3,
  name: "__MSG_appName__",
  version: "3.2.57",
  description: "__MSG_appDesc__",
  default_locale: "vi",
  homepage_url: "https://www.shipxanh.com/",
  icons: {
    "128": "img/logo.png",
  },
  action: {
    // default_popup: 'popup.html',
    default_icon: "img/logo.png",
  },
  options_page: "options.html",
  // devtools_page: 'devtools.html',
  background: {
    service_worker: "src/background/index.ts",
    type: "module",
  },
  content_scripts: [
    {
      matches: [
        "*://www.tiktok.com/shop/sg/pdp/*",
        "*://www.tiktok.com/shop/vn/pdp/*",
        "*://www.tiktok.com/shop/th/pdp/*",
        "*://www.tiktok.com/shop/ph/pdp/*",
        "*://www.tiktok.com/shop/my/pdp/*",
        "*://www.tiktok.com/view/product/*",
        "*://shop.tiktok.com/view/product/*",
        "*://shop-id.tokopedia.com/view/product/*",
        "*://shop-th.tiktok.com/view/product/*",
        "*://shop-vn.tiktok.com/view/product/*",
        "*://shop-sg.tiktok.com/view/product/*",
        "*://shop-ph.tiktok.com/view/product/*",
        "*://shop-my.tiktok.com/view/product/*",
        "*://shop-uk.tiktokw.eu/view/product/*",
        "*://www.tiktok.com/pdp/product/*",
        "*://shop.tiktok.com/pdp/product/*",
        "*://www.tiktok.com/shop/pdp/*",
        "*://shop-id.tokopedia.com/pdp/product/*",
        "*://shop-th.tiktok.com/pdp/product/*",
        "*://shop-vn.tiktok.com/pdp/product/*",
        "*://shop-sg.tiktok.com/pdp/product/*",
        "*://shop-ph.tiktok.com/pdp/product/*",
        "*://shop-my.tiktok.com/pdp/product/*",
        "*://www.tiktok.com/pdp/*",
        "*://shop.tiktok.com/pdp/*",
        "*://shop.tiktok.com/*/pdp/*",
        "*://shop.tiktok.com/*/view/product/*",
        "*://shop-id.tokopedia.com/pdp/*",
        "*://shop-th.tiktok.com/pdp/*",
        "*://shop-vn.tiktok.com/pdp/*",
        "*://shop-sg.tiktok.com/pdp/*",
        "*://shop-ph.tiktok.com/pdp/*",
        "*://shop-my.tiktok.com/pdp/*",
        "*://*.lazada.com.my/*",
        "*://*.lazada.sg/*",
        "*://*.lazada.vn/*",
        "*://*.lazada.co.id/*",
        "*://*.lazada.co.th/*",
        "*://*.lazada.com.ph/*",
        "*://*.taobao.com/*",
        "*://*.jd.co.th/*",
        "*://*.jd.id/*",
        "*://shop.line.me/*",
        "*://*.facebook.com/*",
        "*://*.taobao.com/*",
        "*://*.yangkeduo.com/*",
        "*://*.pinduoduo.com/*",
        "*://*.1688.com/*",
        "*://www.tokopedia.com/*",
        "*://*.lazada.com.my/*",
        "*://*.lazada.sg/*",
        "*://*.lazada.vn/*",
        "*://*.lazada.co.id/*",
        "*://*.lazada.co.th/*",
        "*://*.lazada.com.ph/*",
        "*://*.ocistok.com/*",
        "*://*.sabomall.com/*",
        "*://www.bukalapak.com/*",
        "*://m.bukalapak.com/*",
        "*://www.jakmall.com/*",
        "*://www.sendo.vn/*",
        "*://tiki.vn/*",
        "*://www.blibli.com/*",
        "*://*.1688.com/*",
        "*://*.jd.co.th/*",
        "*://*.jd.id/*",
        "*://*.aliexpress.com/*",
        "*://*.aliexpress.ru/*",
        "*://*.aliexpress.us/*",
        "*://*.jakartanotebook.com/*",
        "*://*.taobao.com/*",
        "*://*.tmall.com/*",
        "*://*.tmall.hk/*",
        "*://*.pinduoduo.com/*",
        "*://*.yangkeduo.com/*",
        "*://yangkeduo.com/*",
        "*://evermos.com/*",
        "*://shop.line.me/*",
        "*://*.facebook.com/*",
        "*://*.2ub2b.com/*",
        "*://www.tiktok.com/shop/sg/pdp/*",
        "*://www.tiktok.com/view/product/*",
        "*://shop.tiktok.com/view/product/*",
        "*://shop-id.tokopedia.com/view/product/*",
        "*://shop-th.tiktok.com/view/product/*",
        "*://shop-vn.tiktok.com/view/product/*",
        "*://shop-sg.tiktok.com/view/product/*",
        "*://shop-ph.tiktok.com/view/product/*",
        "*://shop-my.tiktok.com/view/product/*",
        "*://shop-uk.tiktokw.eu/view/product/*",
        "*://www.tiktok.com/pdp/product/*",
        "*://shop.tiktok.com/pdp/product/*",
        "*://www.tiktok.com/shop/ph/pdp/*",
        "*://www.tiktok.com/shop/vn/pdp/*",
        "*://www.tiktok.com/shop/sg/pdp/*",
        "*://www.tiktok.com/shop/my/pdp/*",
        "*://www.tiktok.com/shop/th/pdp/*",
        "*://www.tiktok.com/shop/pdp/*",
        "*://shop-id.tokopedia.com/pdp/product/*",
        "*://shop-th.tiktok.com/pdp/product/*",
        "*://shop-vn.tiktok.com/pdp/product/*",
        "*://shop-sg.tiktok.com/pdp/product/*",
        "*://shop-ph.tiktok.com/pdp/product/*",
        "*://shop-my.tiktok.com/pdp/product/*",

        "*://www.tiktok.com/pdp/*",
        "*://shop.tiktok.com/pdp/*",
        "*://shop.tiktok.com/*/pdp/*",
        "*://shop.tiktok.com/*/view/product/*",
        "*://shop-id.tokopedia.com/pdp/*",
        "*://shop-th.tiktok.com/pdp/*",
        "*://shop-vn.tiktok.com/pdp/*",
        "*://shop-sg.tiktok.com/pdp/*",
        "*://shop-ph.tiktok.com/pdp/*",
        "*://shop-my.tiktok.com/pdp/*",
        "*://*.1688.com/*",
        "*://detail.1688.com/offer/*",
        "*://order.1688.com/order/*",
        "*://*.aliexpress.com/*",
        "*://*.aliexpress.ru/*",
        "*://*.aliexpress.us/*",
        "*://*.taobao.com/*",
        "*://*.pinduoduo.com/*",
        "*://*.yangkeduo.com/*",
        "*://yangkeduo.com/*",
        "*://*.tmall.com/*",
        "*://*.tmall.hk/*",
        "*://www.tokopedia.com/*",
        "*://shopee.vn/*",
        "*://shopee.com/*",
        "*://shopee.com.my/*",
        "*://shopee.co.id/*",
        "*://shopee.co.th/*",
        "*://shopee.ph/*",
        "*://shopee.com.ph/*",
        "*://shopee.sg/*",
        "*://shopee.com.sg/*",
        "*://shopee.tw/*",
        "*://shopee.com.tw/*",
        "*://seller.shopee.com.my/*",
        "*://seller.shopee.ph/*",
        "*://seller.shopee.sg/*",
        "*://banhang.shopee.vn/*",
        "*://seller.xiapi.shopee.cn/*",
        "*://seller.id.shopee.cn/*",
        "*://seller.th.shopee.cn/*",
        "*://seller.my.shopee.cn/*",
        "*://seller.ph.shopee.cn/*",
        "*://seller.sg.shopee.cn/*",
        "*://seller.vn.shopee.cn/*",
        "*://seller.xiapi.shopee.cn/*",
        "*://seller.shopee.cn/*",
        "*://seller.shopee.tw/*",
        "*://seller.shopee.co.id/*",
        "*://seller.shopee.co.th/*",
      ],
      js: ["src/contentScript/contentApp/index.tsx"],
      run_at: "document_start",
      all_frames: true,
    },
  ],

  side_panel: {
    default_path: "sidepanel.html",
  },
  web_accessible_resources: [
    {
      resources: [
        "img/**",
        "scripts/**",
        "locales/**",
        "assets/**",
        "src/**",
        "COMPONENTS/**",
        "contentApp/**",
        "contentScript/**",
      ],
      matches: ["http://*/*", "https://*/*"],
    },
  ],
  permissions: [
    "sidePanel",
    "storage",
    "tabs",
    "activeTab",
    "webRequest",
    "scripting",
  ],
  host_permissions: ["<all_urls>"],
  externally_connectable: {
    matches: ["*://*.shipxanh.com/*", "*://localhost/*"],
  },
  content_security_policy: {
    extension_pages: "script-src 'self'; object-src 'self';",
    sandbox: "sandbox allow-scripts; script-src 'self'; object-src 'self';",
  },
});
