import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MoreHorizontal } from "lucide-react";
import { useTranslation } from "~i18n";
export const PremiumToolCard = ({ tool, onClick, onToggle, isActive = false, compact = false, showToggle = true }) => {
    const { t } = useTranslation();
    const handleToggle = (e) => {
        if (onToggle) {
            e.stopPropagation();
            onToggle(!isActive);
        }
    };
    return (_jsxs("div", { onClick: onClick, className: `group relative bg-[rgb(var(--bg-card))] border border-[rgba(var(--border-main),var(--border-opacity))] rounded-3xl cursor-pointer transition-all hover:bg-[rgb(var(--bg-card-hover))] hover:border-blue-500/30 hover:shadow-2xl active:scale-[0.98] flex flex-col gap-4 ${isActive ? "ring-2 ring-blue-500/50 bg-[rgb(var(--bg-card-hover))] shadow-[0_0_20px_rgba(59,130,246,0.15)]" : ""} ${compact ? "p-4 gap-3" : "p-5 gap-4"}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex items-center justify-center transition-all group-hover:scale-110", children: _jsx(tool.icon, { size: compact ? 24 : 28, style: { color: tool.color || '#8b949e' } }) }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: `${compact ? "text-xs" : "text-sm"} font-bold text-[rgb(var(--text-main))]`, children: tool.i18nKey ? t(tool.i18nKey) : tool.name }), _jsx("span", { className: "text-[10px] text-[rgb(var(--text-muted))] font-medium uppercase tracking-wider", children: "v0.4.12" })] })] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [!compact && (_jsx("div", { className: "p-2 hover:bg-white/5 rounded-xl transition-colors", children: _jsx(MoreHorizontal, { size: 16, className: "text-gray-500" }) })), showToggle && (_jsx("div", { onClick: handleToggle, className: `w-10 h-5 rounded-full relative transition-colors cursor-pointer ${isActive ? 'bg-blue-600' : 'bg-gray-700'}`, children: _jsx("div", { className: `absolute top-1 w-3 h-3 bg-white rounded-full transition-all ${isActive ? 'left-6' : 'left-1'}` }) }))] })] }), _jsx("div", { className: "flex-1", children: _jsx("p", { className: `text-[11px] leading-relaxed text-[rgb(var(--text-muted))] font-medium ${compact ? "line-clamp-2" : "line-clamp-3"}`, children: tool.description || t(`${tool.i18nKey || tool.name.toLowerCase().replace(/\s+/g, '_')}_desc`) || "Giải thích cách công cụ này hoạt động để giúp bạn tối ưu hóa quy trình làm việc trên mạng xã hội." }) }), !compact && (_jsxs("div", { className: "pt-2 border-t border-white/5 flex items-center justify-between", children: [_jsx("span", { className: "text-[10px] text-gray-500 font-medium", children: "Updated: Just now" }), tool.shortcut && (_jsx("span", { className: "text-[9px] font-bold text-blue-400 bg-blue-400/10 px-2 py-0.5 rounded-lg", children: tool.shortcut }))] }))] }));
};
//# sourceMappingURL=PremiumToolCard.js.map