export interface YouTubeTranscriptSegment {
  timestamp: string;
  seconds: number;
  text: string;
}

export interface YouTubeCaptionTrack {
  name: string;
  languageCode: string;
  kind?: string;
  vssId?: string;
  isAutoGenerated: boolean;
  baseUrl?: string;
}

export interface YouTubeTranscriptEndpoint {
  params: string;
  targetId?: string;
  apiUrl?: string;
}

export interface YouTubePlaybackState {
  platform: "youtube";
  title: string;
  channel: string;
  currentTimeSeconds: number;
  durationSeconds: number;
  paused: boolean;
}

const TRANSCRIPT_SEGMENT_SELECTOR = [
  "ytd-transcript-segment-renderer",
  "yt-transcript-segment-renderer",
  "[class*='transcript-segment']",
].join(",");
const TRANSCRIPT_PANEL_SELECTOR = [
  "ytd-engagement-panel-section-list-renderer",
  "ytd-transcript-renderer",
  "yt-transcript-renderer",
].join(",");
const TRANSCRIPT_TIMESTAMP_SELECTOR = [
  ".segment-timestamp",
  "#timestamp",
  "[class*='timestamp']",
].join(",");
const TRANSCRIPT_TEXT_SELECTOR = [
  ".segment-text",
  "#segment-text",
  "yt-formatted-string.segment-text",
  "[class*='segment-text']",
].join(",");
const MAX_TRANSCRIPT_SEGMENTS = 160;
const MAX_TRANSCRIPT_TEXT_LENGTH = 24_000;
const MAX_TRANSCRIPT_DISCOVERY_NODES = 32;

export function isYouTubeUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.hostname === "www.youtube.com" || parsed.hostname === "youtube.com" || parsed.hostname === "youtu.be";
  } catch {
    return false;
  }
}

export function isYouTubeVideoUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    if (!isYouTubeUrl(url)) {
      return false;
    }
    if (parsed.hostname === "youtu.be") {
      return parsed.pathname.split("/").filter(Boolean).length > 0;
    }
    return parsed.pathname === "/watch" || parsed.pathname.startsWith("/shorts/") || parsed.pathname.startsWith("/live/");
  } catch {
    return false;
  }
}

export function parseTimestampToSeconds(value: string): number {
  const parts = value
    .split(":")
    .map((part) => Number.parseInt(part, 10))
    .filter((part) => Number.isFinite(part));

  return parts.reduce((total, part) => total * 60 + part, 0);
}

export function toSeekActionId(timestamp: string): string {
  return `seek-${parseTimestampToSeconds(timestamp)}`;
}

export function collectYouTubePlaybackState(
  root: Pick<Document, "querySelector" | "querySelectorAll" | "title"> = document,
  url = window.location.href,
): YouTubePlaybackState | null {
  if (!isYouTubeVideoUrl(url)) {
    return null;
  }

  const video = findPrimaryVideo(root);
  return {
    platform: "youtube",
    title:
      root.querySelector("h1.ytd-watch-metadata yt-formatted-string")?.textContent?.trim()
      ?? root.title,
    channel: root.querySelector("#owner #channel-name a")?.textContent?.trim() ?? "",
    currentTimeSeconds: video ? Math.floor(video.currentTime) : 0,
    durationSeconds: video && Number.isFinite(video.duration) ? Math.floor(video.duration) : 0,
    paused: video ? video.paused : true,
  };
}

export function collectYouTubeTranscriptSegmentsFromDocument(
  root: Pick<Document, "querySelectorAll"> = document,
): YouTubeTranscriptSegment[] {
  const seen = new Set<string>();
  const segments: YouTubeTranscriptSegment[] = [];

  for (const node of Array.from(root.querySelectorAll(TRANSCRIPT_SEGMENT_SELECTOR)).slice(0, MAX_TRANSCRIPT_SEGMENTS * 2)) {
    const segment = parseTranscriptSegmentNode(node);
    if (!segment) {
      continue;
    }
    const key = `${segment.timestamp}\n${segment.text}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    segments.push(segment);
    if (segments.length >= MAX_TRANSCRIPT_SEGMENTS) {
      break;
    }
  }

  return segments;
}

export function collectYouTubeTranscriptEndpointFromDocument(
  root: Pick<Document, "querySelectorAll"> = document,
): YouTubeTranscriptEndpoint | null {
  for (const node of Array.from(root.querySelectorAll(TRANSCRIPT_PANEL_SELECTOR)).slice(0, MAX_TRANSCRIPT_DISCOVERY_NODES)) {
    const data = getElementData(node);
    const endpoint = findTranscriptEndpoint(data);
    if (endpoint) {
      return endpoint;
    }
  }
  return null;
}

export function collectYouTubeCaptionTracksFromPlayerResponse(source: unknown = globalThis): YouTubeCaptionTrack[] {
  const response = readPath(source, ["ytInitialPlayerResponse"]);
  const tracks = readPath(response, ["captions", "playerCaptionsTracklistRenderer", "captionTracks"]);
  if (!Array.isArray(tracks)) {
    return [];
  }

  return tracks
    .map((track): YouTubeCaptionTrack | null => {
      if (!isRecord(track)) {
        return null;
      }
      const baseUrl = typeof track.baseUrl === "string" ? track.baseUrl : undefined;
      const languageCode = typeof track.languageCode === "string" ? track.languageCode : "";
      const kind = typeof track.kind === "string" ? track.kind : undefined;
      const vssId = typeof track.vssId === "string" ? track.vssId : undefined;
      const name = normalizeTranscriptText(readText(track.name));
      if (!languageCode && !name && !baseUrl) {
        return null;
      }
      const captionTrack: YouTubeCaptionTrack = {
        name,
        languageCode,
        isAutoGenerated: kind === "asr" || Boolean(vssId?.startsWith("a.")),
      };
      if (kind) {
        captionTrack.kind = kind;
      }
      if (vssId) {
        captionTrack.vssId = vssId;
      }
      if (baseUrl) {
        captionTrack.baseUrl = baseUrl;
      }
      return captionTrack;
    })
    .filter((track): track is YouTubeCaptionTrack => track !== null)
    .slice(0, 20);
}

export function parseYouTubeTranscriptRendererResponse(value: unknown): YouTubeTranscriptSegment[] {
  const segments: YouTubeTranscriptSegment[] = [];
  const seen = new Set<string>();
  walkJson(value, (node) => {
    if (!isRecord(node)) {
      return;
    }
    const renderer = node.transcriptSegmentRenderer;
    if (!isRecord(renderer)) {
      return;
    }
    const segment = parseTranscriptRendererSegment(renderer);
    if (!segment) {
      return;
    }
    const key = `${segment.timestamp}\n${segment.text}`;
    if (seen.has(key)) {
      return;
    }
    seen.add(key);
    segments.push(segment);
  });
  return segments.slice(0, MAX_TRANSCRIPT_SEGMENTS);
}

export function parseTimedTextJson3(value: unknown): YouTubeTranscriptSegment[] {
  const events = readPath(value, ["events"]);
  if (!Array.isArray(events)) {
    return [];
  }

  const segments: YouTubeTranscriptSegment[] = [];
  for (const event of events) {
    if (!isRecord(event)) {
      continue;
    }
    const startMs = typeof event.tStartMs === "number" ? event.tStartMs : Number(event.tStartMs);
    const segs = event.segs;
    if (!Number.isFinite(startMs) || !Array.isArray(segs)) {
      continue;
    }
    const text = normalizeTranscriptText(
      segs
        .map((seg) => (isRecord(seg) && typeof seg.utf8 === "string" ? seg.utf8 : ""))
        .join(""),
    );
    if (!text) {
      continue;
    }
    segments.push(segmentFromMilliseconds(startMs, text));
    if (segments.length >= MAX_TRANSCRIPT_SEGMENTS) {
      break;
    }
  }

  return segments;
}

export function parseTimedTextVtt(value: string): YouTubeTranscriptSegment[] {
  const segments: YouTubeTranscriptSegment[] = [];
  const blocks = value.replace(/\r/gu, "").split(/\n\n+/u);
  for (const block of blocks) {
    const lines = block.split("\n").map((line) => line.trim()).filter(Boolean);
    const timingLine = lines.find((line) => line.includes("-->"));
    if (!timingLine) {
      continue;
    }
    const text = normalizeTranscriptText(lines.slice(lines.indexOf(timingLine) + 1).join(" "));
    if (!text) {
      continue;
    }
    const timestamp = timingLine.split("-->")[0]?.trim() ?? "";
    segments.push(segmentFromMilliseconds(parseVttTimestampToMilliseconds(timestamp), text));
    if (segments.length >= MAX_TRANSCRIPT_SEGMENTS) {
      break;
    }
  }
  return segments;
}

export async function collectYouTubeAdapterPayload(): Promise<Record<string, unknown> | null> {
  const url = window.location.href;
  if (!isYouTubeVideoUrl(url)) {
    return null;
  }

  const playbackState = collectYouTubePlaybackState(document, url) ?? {
    platform: "youtube" as const,
    title: document.title,
    channel: "",
    currentTimeSeconds: 0,
    durationSeconds: 0,
    paused: true,
  };
  const description =
    document.querySelector("#description-inline-expander")?.textContent?.trim()
    ?? document.querySelector("#description")?.textContent?.trim()
    ?? "";
  let transcriptSegments = collectYouTubeTranscriptSegmentsFromDocument(document);
  let transcriptSource = transcriptSegments.length > 0 ? "visible-dom" : "unavailable";
  let transcriptFetchError = "";
  const transcriptEndpoint = collectYouTubeTranscriptEndpointFromDocument(document);
  const captionTracks = collectYouTubeCaptionTracksFromPlayerResponse(window);

  if (!transcriptSegments.length && transcriptEndpoint) {
    try {
      const fetchedSegments = await fetchTranscriptSegmentsFromInnertube(transcriptEndpoint);
      if (fetchedSegments.length) {
        transcriptSegments = fetchedSegments;
        transcriptSource = "youtubei-get-transcript";
      } else {
        transcriptSource = "youtube-transcript-endpoint";
      }
    } catch (error) {
      transcriptSource = "youtube-transcript-endpoint";
      transcriptFetchError = error instanceof Error ? error.message : String(error);
    }
  }

  if (!transcriptSegments.length && captionTracks.length) {
    try {
      const fetched = await fetchTranscriptSegmentsFromCaptionTracks(captionTracks);
      if (fetched.segments.length) {
        transcriptSegments = fetched.segments;
        transcriptSource = fetched.source;
      } else if (transcriptSource === "unavailable") {
        transcriptSource = "youtube-caption-tracks";
      }
    } catch (error) {
      if (transcriptSource === "unavailable") {
        transcriptSource = "youtube-caption-tracks";
      }
      transcriptFetchError = transcriptFetchError || (error instanceof Error ? error.message : String(error));
    }
  }

  return {
    ...playbackState,
    description: description.slice(0, 2000),
    transcriptAvailable: transcriptSegments.length > 0 || Boolean(transcriptEndpoint) || captionTracks.length > 0,
    transcriptSource,
    transcriptEndpoint: transcriptEndpoint ? sanitizeTranscriptEndpoint(transcriptEndpoint) : null,
    transcriptFetchError,
    captionTracks: captionTracks.map(stripCaptionTrackBaseUrl),
    transcriptSegments,
    transcriptText: formatTranscriptText(transcriptSegments),
    chapterTitles: Array.from(document.querySelectorAll("ytd-macro-markers-list-item-renderer"))
      .map((node) => node.textContent?.trim())
      .filter(Boolean)
      .slice(0, 12),
  };
}

function findPrimaryVideo(root: Pick<Document, "querySelector" | "querySelectorAll">): HTMLVideoElement | null {
  const videos = Array.from(root.querySelectorAll("video")) as HTMLVideoElement[];
  return (
    videos.find((video) => !video.paused) ??
    videos.find((video) => video.currentTime > 0) ??
    videos.find((video) => Number.isFinite(video.duration) && video.duration > 0) ??
    (root.querySelector("video") as HTMLVideoElement | null)
  );
}

async function fetchTranscriptSegmentsFromInnertube(endpoint: YouTubeTranscriptEndpoint): Promise<YouTubeTranscriptSegment[]> {
  const ytcfg = readPath(window, ["ytcfg"]);
  const data = isRecord(ytcfg) && typeof ytcfg.data_ === "object" ? ytcfg.data_ : null;
  const apiKey = typeof readPath(data, ["INNERTUBE_API_KEY"]) === "string"
    ? String(readPath(data, ["INNERTUBE_API_KEY"]))
    : "";
  const clientName = typeof readPath(data, ["INNERTUBE_CLIENT_NAME"]) === "string"
    ? String(readPath(data, ["INNERTUBE_CLIENT_NAME"]))
    : "WEB";
  const clientVersion = typeof readPath(data, ["INNERTUBE_CLIENT_VERSION"]) === "string"
    ? String(readPath(data, ["INNERTUBE_CLIENT_VERSION"]))
    : "";
  if (!apiKey || !clientVersion) {
    return [];
  }

  const response = await fetch(`/youtubei/v1/get_transcript?key=${encodeURIComponent(apiKey)}&prettyPrint=false`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName,
          clientVersion,
          hl: document.documentElement.lang || navigator.language || "en",
          gl: "US",
        },
      },
      params: endpoint.params,
    }),
    credentials: "same-origin",
  });
  if (!response.ok) {
    throw new Error(`YouTube transcript endpoint returned ${response.status}`);
  }
  return parseYouTubeTranscriptRendererResponse(await response.json());
}

async function fetchTranscriptSegmentsFromCaptionTracks(
  tracks: YouTubeCaptionTrack[],
): Promise<{ source: string; segments: YouTubeTranscriptSegment[] }> {
  const track = chooseCaptionTrack(tracks);
  if (!track?.baseUrl) {
    return { source: "youtube-caption-tracks", segments: [] };
  }

  const jsonUrl = withTimedTextFormat(track.baseUrl, "json3");
  const jsonResponse = await fetch(jsonUrl, { credentials: "same-origin" });
  const jsonText = await jsonResponse.text();
  if (jsonResponse.ok && jsonText.trim()) {
    try {
      const jsonSegments = parseTimedTextJson3(JSON.parse(jsonText));
      if (jsonSegments.length) {
        return { source: "timedtext-json3", segments: jsonSegments };
      }
    } catch {
      // Some YouTube responses ignore fmt=json3. Fall through to WebVTT.
    }
  }

  const vttResponse = await fetch(withTimedTextFormat(track.baseUrl, "vtt"), { credentials: "same-origin" });
  const vttText = await vttResponse.text();
  if (vttResponse.ok && vttText.trim()) {
    const vttSegments = parseTimedTextVtt(vttText);
    if (vttSegments.length) {
      return { source: "timedtext-vtt", segments: vttSegments };
    }
  }

  return { source: "youtube-caption-tracks", segments: [] };
}

function chooseCaptionTrack(tracks: YouTubeCaptionTrack[]): YouTubeCaptionTrack | null {
  const preferredLanguages = getPreferredCaptionLanguages();
  for (const language of preferredLanguages) {
    const manual = tracks.find((track) => isCaptionLanguageMatch(track.languageCode, language) && !track.isAutoGenerated);
    if (manual) {
      return manual;
    }
  }
  return tracks.find((track) => !track.isAutoGenerated) ?? tracks[0] ?? null;
}

function getPreferredCaptionLanguages(): string[] {
  const browserLanguages = Array.isArray(navigator.languages) && navigator.languages.length
    ? navigator.languages
    : [navigator.language];
  const normalized = browserLanguages.map(normalizeCaptionLanguage).filter(Boolean);
  return Array.from(new Set([...normalized, "en"]));
}

function isCaptionLanguageMatch(trackLanguage: string, preferredLanguage: string): boolean {
  const track = normalizeCaptionLanguage(trackLanguage);
  const preferred = normalizeCaptionLanguage(preferredLanguage);
  return Boolean(track && preferred && (track === preferred || track.split("-")[0] === preferred.split("-")[0]));
}

function normalizeCaptionLanguage(value: string | undefined): string {
  return (value ?? "").trim().replaceAll("_", "-").toLowerCase();
}

function withTimedTextFormat(value: string, format: "json3" | "vtt"): string {
  const url = new URL(value, window.location.href);
  url.searchParams.set("fmt", format);
  return url.toString();
}

function parseTranscriptSegmentNode(node: Element): YouTubeTranscriptSegment | null {
  const timestamp =
    node.querySelector(TRANSCRIPT_TIMESTAMP_SELECTOR)?.textContent?.trim() ??
    extractTimestamp(node.textContent ?? "");
  if (!timestamp) {
    return null;
  }

  const text =
    node.querySelector(TRANSCRIPT_TEXT_SELECTOR)?.textContent?.trim() ??
    extractTranscriptTextFromCombinedNodeText(node.textContent ?? "", timestamp);
  const normalizedText = normalizeTranscriptText(text);
  if (!normalizedText) {
    return null;
  }

  return {
    timestamp,
    seconds: parseTimestampToSeconds(timestamp),
    text: normalizedText,
  };
}

function formatTranscriptText(segments: YouTubeTranscriptSegment[]): string {
  if (!segments.length) {
    return "";
  }
  return segments
    .map((segment) => `${segment.timestamp} ${segment.text}`)
    .join("\n")
    .slice(0, MAX_TRANSCRIPT_TEXT_LENGTH);
}

function parseTranscriptRendererSegment(renderer: Record<string, unknown>): YouTubeTranscriptSegment | null {
  const rawStartMs = renderer.startMs ?? renderer.startTimeMs;
  const startMs = typeof rawStartMs === "number" ? rawStartMs : Number(rawStartMs);
  const text = normalizeTranscriptText(readText(renderer.snippet) || readText(renderer.text));
  if (!Number.isFinite(startMs) || !text) {
    return null;
  }
  return segmentFromMilliseconds(startMs, text);
}

function segmentFromMilliseconds(milliseconds: number, text: string): YouTubeTranscriptSegment {
  const seconds = Math.max(0, Math.floor(milliseconds / 1000));
  return {
    timestamp: formatSecondsAsTimestamp(seconds),
    seconds,
    text,
  };
}

function formatSecondsAsTimestamp(seconds: number): string {
  const safeSeconds = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(safeSeconds / 3600);
  const minutes = Math.floor((safeSeconds % 3600) / 60);
  const remainingSeconds = safeSeconds % 60;
  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(remainingSeconds).padStart(2, "0")}`;
  }
  return `${minutes}:${String(remainingSeconds).padStart(2, "0")}`;
}

function parseVttTimestampToMilliseconds(value: string): number {
  const match = /^(?:(\d+):)?(\d{1,2}):(\d{2})(?:\.(\d{1,3}))?$/u.exec(value.trim());
  if (!match) {
    return 0;
  }
  const hours = Number(match[1] ?? 0);
  const minutes = Number(match[2] ?? 0);
  const seconds = Number(match[3] ?? 0);
  const milliseconds = Number((match[4] ?? "0").padEnd(3, "0"));
  return ((hours * 3600 + minutes * 60 + seconds) * 1000) + milliseconds;
}

function findTranscriptEndpoint(value: unknown): YouTubeTranscriptEndpoint | null {
  let found: YouTubeTranscriptEndpoint | null = null;
  walkJson(value, (node) => {
    if (found || !isRecord(node)) {
      return;
    }
    const endpoint = node.getTranscriptEndpoint;
    if (!isRecord(endpoint) || typeof endpoint.params !== "string") {
      return;
    }
    const transcriptEndpoint: YouTubeTranscriptEndpoint = {
      params: endpoint.params,
    };
    const targetId = readPath(value, ["targetId"]);
    if (typeof targetId === "string") {
      transcriptEndpoint.targetId = targetId;
    }
    const apiUrl = readPath(node, ["commandMetadata", "webCommandMetadata", "apiUrl"]);
    if (typeof apiUrl === "string") {
      transcriptEndpoint.apiUrl = apiUrl;
    }
    found = transcriptEndpoint;
  });
  return found;
}

function getElementData(node: unknown): unknown {
  if (isRecord(node) && "data" in node) {
    return node.data;
  }
  return null;
}

function walkJson(value: unknown, visit: (node: unknown) => void, seen = new WeakSet<object>()): void {
  visit(value);
  if (!isRecord(value) && !Array.isArray(value)) {
    return;
  }
  if (seen.has(value)) {
    return;
  }
  seen.add(value);
  if (Array.isArray(value)) {
    for (const item of value) {
      walkJson(item, visit, seen);
    }
    return;
  }
  for (const item of Object.values(value)) {
    walkJson(item, visit, seen);
  }
}

function readPath(value: unknown, path: string[]): unknown {
  let current = value;
  for (const key of path) {
    if (!isRecord(current)) {
      return undefined;
    }
    current = current[key];
  }
  return current;
}

function readText(value: unknown): string {
  if (typeof value === "string") {
    return value;
  }
  if (!isRecord(value)) {
    return "";
  }
  if (typeof value.simpleText === "string") {
    return value.simpleText;
  }
  if (Array.isArray(value.runs)) {
    return value.runs.map((run) => (isRecord(run) && typeof run.text === "string" ? run.text : "")).join("");
  }
  return "";
}

function sanitizeTranscriptEndpoint(endpoint: YouTubeTranscriptEndpoint): YouTubeTranscriptEndpoint {
  const sanitized: YouTubeTranscriptEndpoint = {
    params: endpoint.params ? "available" : "",
  };
  if (endpoint.targetId) {
    sanitized.targetId = endpoint.targetId;
  }
  if (endpoint.apiUrl) {
    sanitized.apiUrl = endpoint.apiUrl;
  }
  return sanitized;
}

function stripCaptionTrackBaseUrl(track: YouTubeCaptionTrack): Omit<YouTubeCaptionTrack, "baseUrl"> {
  const { baseUrl: _baseUrl, ...safeTrack } = track;
  return safeTrack;
}

function extractTimestamp(value: string): string {
  return /(?:^|\s)(\d{1,2}:\d{2}(?::\d{2})?)(?:\s|$)/u.exec(value)?.[1] ?? "";
}

function extractTranscriptTextFromCombinedNodeText(value: string, timestamp: string): string {
  return value
    .replace(timestamp, " ")
    .replace(/\b\d{1,2}:\d{2}(?::\d{2})?\b/gu, " ")
    .trim();
}

function normalizeTranscriptText(value: string): string {
  return value.replace(/\s+/gu, " ").trim();
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object";
}
